import { describe, expect, it } from 'vitest'
import { createSessionManager } from './session-manager.js'
import { InMemorySessionStorage } from './session-storage-fake.js'
import { SessionConflictError, saveSessionTo } from './session-storage.js'
import type { NormalizedMessageParam } from './providers/types.js'

const msg = (text: string): NormalizedMessageParam =>
  ({ role: 'user', content: text } as NormalizedMessageParam)

/** Seed messages with explicit ids + a _snapshot payload to verify stripping. */
function seedMessages() {
  return [
    { id: 'u1', role: 'user', content: 'one' },
    { id: 'u2', role: 'assistant', content: [{ type: 'text', text: 'two' }], _snapshot: { beforeHash: 'h' } },
    { id: 'u3', role: 'user', content: 'three' },
  ] as unknown as NormalizedMessageParam[]
}

async function seededFake() {
  const fake = new InMemorySessionStorage()
  // Explicit createdAt keeps the fork's createdAt comparison deterministic
  // (seed and fork must never share a same-millisecond timestamp).
  await saveSessionTo(fake, 'src-1', seedMessages(),
    { cwd: '/w', model: 'm', createdAt: '2020-01-01T00:00:00.000Z' }, { expectedRevision: null })
  return fake
}

describe('SessionManager.fork (issue #4)', () => {
  it('invariants: truncation includes anchor, _snapshot stripped, ids regenerated, summary + messageCount', async () => {
    const mgr = createSessionManager({ storage: await seededFake() })
    const forkId = await mgr.fork({ sessionId: 'src-1', messageId: 'u2' }, 'fork-a')
    expect(forkId).toBe('fork-a')
    const data = await mgr.get('fork-a')
    expect(data!.messages).toHaveLength(2)                                   // anchor INCLUDED (truncated at u2)
    expect((data!.messages[1] as any)._snapshot).toBeUndefined()             // stripped
    expect(data!.messages[0].id).not.toBe('u1')                              // ids regenerated by default
    expect(data!.metadata.summary).toBe('Forked from session src-1')
    expect(data!.metadata.messageCount).toBe(2)
    expect(data!.metadata.createdAt).not.toBe('2020-01-01T00:00:00.000Z')
  })

  it('anchor missing → throws', async () => {
    const mgr = createSessionManager({ storage: await seededFake() })
    await expect(mgr.fork({ sessionId: 'src-1', messageId: 'u9' })).rejects.toThrow('Message not found: u9')
  })

  it('preserveIds: true keeps original ids', async () => {
    const mgr = createSessionManager({ storage: await seededFake() })
    await mgr.fork({ sessionId: 'src-1', messageId: 'u2' }, 'fork-p', { preserveIds: true })
    const data = await mgr.get('fork-p')
    expect(data!.messages.map((m) => m.id)).toEqual(['u1', 'u2'])
  })

  it('create-only target: two forks racing the same newSessionId → second throws SessionConflictError', async () => {
    const mgr = createSessionManager({ storage: await seededFake() })
    await mgr.fork({ sessionId: 'src-1' }, 'fork-race')
    await expect(mgr.fork({ sessionId: 'src-1' }, 'fork-race')).rejects.toThrow(SessionConflictError)
  })

  it('snapshot semantics: source mutated after load does not fail the fork', async () => {
    const fake = await seededFake()
    // load() side-effect: after returning the snapshot, mutate the stored source
    const originalLoad = fake.load.bind(fake)
    let armed = false
    fake.load = async (id: string) => {
      const data = await originalLoad(id)
      if (armed && id === 'src-1' && data) {
        await saveSessionTo(fake, 'src-1', [msg('changed')], { cwd: '/w', model: 'm' },
          { expectedRevision: fake.store.get('src-1')!.metadata.revision ?? 0 })
      }
      return data
    }
    armed = true
    const mgr = createSessionManager({ storage: fake })
    const forkId = await mgr.fork({ sessionId: 'src-1', messageId: 'u2' }, 'fork-snap')
    expect(forkId).toBe('fork-snap')
    const data = await mgr.get('fork-snap')
    expect(data!.messages).toHaveLength(2)  // snapshot at load time, not the mutated 1-message source
  })
})

describe('SessionManager delete/list (issue #4)', () => {
  it('routes to the injected backend; unsupported methods throw', async () => {
    const fake = await seededFake()
    const mgr = createSessionManager({ storage: fake })
    expect((await mgr.list()).map((m) => m.id)).toContain('src-1')
    expect(await mgr.delete('src-1')).toBe(true)
    expect(await mgr.get('src-1')).toBeNull()
    expect(await mgr.getMessages('src-1')).toEqual([])

    const minimal = { load: async () => null, save: async () => {} }
    const bare = createSessionManager({ storage: minimal })
    await expect(bare.delete('x')).rejects.toThrow('SessionStorage.delete not implemented by backend')
    await expect(bare.list()).rejects.toThrow('SessionStorage.list not implemented by backend')
  })
})
