/**
 * Session Storage & Management
 *
 * Persists conversation transcripts to disk for resumption.
 * Manages session lifecycle (create, resume, list, fork).
 */

import { defaultSessionStorage, loadSessionFrom, saveSessionTo, type SessionStorage, type SaveOptions } from './session-storage.js'
import type { NormalizedMessageParam } from './providers/types.js'

/**
 * Session metadata.
 */
export interface SessionMetadata {
  id: string
  cwd: string
  model: string
  provider?: string
  createdAt: string
  updatedAt: string
  messageCount: number
  summary?: string
  lastInputTokens?: number
  lastOutputTokens?: number
  /** FindTool-activated deferred tool names (issue #115). Optional: sessions
   * saved by older SDK versions have no such field. */
  activatedTools?: string[]
  /** 会话标签（tagSession）。原为 as any 写入，issue #4 正式入型。 */
  tag?: string | null
  /** 乐观并发版本号，单调递增。仅 CAS 写路径写入；legacy 路径不写。 */
  revision?: number
}

/**
 * Session data on disk.
 */
export interface SessionData {
  metadata: SessionMetadata
  messages: NormalizedMessageParam[]
}

/**
 * Save session to disk.
 */
export async function saveSession(
  sessionId: string,
  messages: NormalizedMessageParam[],
  metadata: Partial<SessionMetadata>,
): Promise<void> {
  return saveSessionTo(defaultSessionStorage, sessionId, messages, metadata)
}

/**
 * Load session from disk.
 */
export async function loadSession(sessionId: string): Promise<SessionData | null> {
  return loadSessionFrom(defaultSessionStorage, sessionId)
}

/**
 * List all sessions.
 */
export async function listSessions(): Promise<SessionMetadata[]> {
  return (await defaultSessionStorage.list?.()) ?? []
}

/**
 * Fork source specification — which session and message to fork from.
 */
export interface ForkSource {
  sessionId: string
  /** Fork point: only messages up to and including this one are copied. */
  messageId?: string
}

/**
 * Fork options.
 */
export interface ForkOptions {
  /**
   * Keep original message IDs instead of regenerating them.
   *
   * Message IDs are only required to be unique within a session, so reusing
   * them across sessions is safe. Useful when the caller stores SDK messages
   * in a database keyed by (sessionId, messageId) and wants the forked
   * transcript to reference the same records.
   *
   * Defaults to `false` (IDs are regenerated).
   */
  preserveIds?: boolean
}

/**
 * storage-aware fork core (issue #4). Legacy `forkSession` binds the default
 * file backend with NO save opts (upsert); SessionManager passes
 * `{ expectedRevision: null }` (create-only target, spec §8 snapshot semantics).
 */
export async function forkSessionWith(
  storage: SessionStorage,
  source: ForkSource | string,
  newSessionId?: string,
  options?: ForkOptions,
  saveOpts?: SaveOptions,
): Promise<string | null> {
  // Accept both old signature (string) and new ({ sessionId, messageId? })
  const sourceSessionId = typeof source === 'string' ? source : source.sessionId
  const forkMessageId = typeof source === 'string' ? undefined : source.messageId

  const data = await loadSessionFrom(storage, sourceSessionId)
  if (!data) return null

  let messages = data.messages

  if (forkMessageId) {
    const idx = messages.findIndex((m) => m.id === forkMessageId)
    if (idx === -1) {
      throw new Error(`Message not found: ${forkMessageId}`)
    }
    messages = messages.slice(0, idx + 1)
  }

  // Strip _snapshot — fork only supports conversation revert, not file revert.
  messages = messages.map((m) => ({
    ...m,
    id: options?.preserveIds ? m.id : crypto.randomUUID(),
    _snapshot: undefined,
  }))

  const forkId = newSessionId || crypto.randomUUID()

  await saveSessionTo(storage, forkId, messages, {
    ...data.metadata,
    id: forkId,
    createdAt: new Date().toISOString(),
    summary: `Forked from session ${sourceSessionId}`,
  }, saveOpts)

  return forkId
}

/**
 * Fork a session (create a copy with a new ID).
 *
 * Without messageId: full copy of all messages.
 * With messageId: only messages up to and including that message are copied.
 *
 * Message IDs are regenerated by default; set `preserveIds: true` to keep the
 * original IDs. `_snapshot` metadata is always stripped — fork only supports
 * conversation revert, not file revert (avoids cross-session file conflicts).
 */
export async function forkSession(
  source: ForkSource | string,
  newSessionId?: string,
  options?: ForkOptions,
): Promise<string | null> {
  return forkSessionWith(defaultSessionStorage, source, newSessionId, options)
}

/**
 * Get session messages.
 */
export async function getSessionMessages(
  sessionId: string,
): Promise<NormalizedMessageParam[]> {
  const data = await loadSession(sessionId)
  return data?.messages || []
}

/**
 * Append a message to a session transcript.
 */
export async function appendToSession(
  sessionId: string,
  message: NormalizedMessageParam,
): Promise<void> {
  const data = await loadSession(sessionId)
  if (!data) return

  data.messages.push(message.id ? message : { ...message, id: crypto.randomUUID() })
  data.metadata.updatedAt = new Date().toISOString()
  data.metadata.messageCount = data.messages.length

  await saveSession(sessionId, data.messages, data.metadata)
}

/**
 * Delete a session.
 */
export async function deleteSession(sessionId: string): Promise<boolean> {
  return (await defaultSessionStorage.delete?.(sessionId)) ?? false
}

/**
 * Get info about a specific session.
 */
export async function getSessionInfo(
  sessionId: string,
  options?: { dir?: string },
): Promise<SessionMetadata | null> {
  const data = await loadSession(sessionId)
  return data?.metadata || null
}

/**
 * Rename a session.
 */
export async function renameSession(
  sessionId: string,
  title: string,
  options?: { dir?: string },
): Promise<void> {
  const data = await loadSession(sessionId)
  if (!data) return

  data.metadata.summary = title
  data.metadata.updatedAt = new Date().toISOString()

  await saveSession(sessionId, data.messages, data.metadata)
}

/**
 * Tag a session.
 */
export async function tagSession(
  sessionId: string,
  tag: string | null,
  options?: { dir?: string },
): Promise<void> {
  const data = await loadSession(sessionId)
  if (!data) return

  data.metadata.tag = tag
  data.metadata.updatedAt = new Date().toISOString()

  await saveSession(sessionId, data.messages, data.metadata)
}
