/**
 * Session Storage & Management
 *
 * Persists conversation transcripts to disk for resumption.
 * Manages session lifecycle (create, resume, list, fork).
 */

import { readFile, writeFile, mkdir, readdir, rename, unlink } from 'fs/promises'
import { join } from 'path'
import type { NormalizedMessageParam } from './providers/types.js'

/**
 * Ensure every message has a stable id.
 */
function ensureMessageIds(messages: NormalizedMessageParam[]): NormalizedMessageParam[] {
  for (const msg of messages) {
    if (!msg.id) msg.id = crypto.randomUUID()
  }
  return messages
}

/**
 * Session metadata.
 */
export interface SessionMetadata {
  id: string
  cwd: string
  model: string
  provider?: string
  createdAt: string
  updatedAt: string
  messageCount: number
  summary?: string
  lastInputTokens?: number
  lastOutputTokens?: number
}

/**
 * Session data on disk.
 */
export interface SessionData {
  metadata: SessionMetadata
  messages: NormalizedMessageParam[]
}

/**
 * Get the sessions directory path.
 */
function getSessionsDir(): string {
  const home = process.env.HOME || process.env.USERPROFILE || '/tmp'
  return join(home, '.agents', 'sessions')
}

/**
 * Get the path for a specific session.
 */
function getSessionPath(sessionId: string): string {
  return join(getSessionsDir(), sessionId)
}

/**
 * Save session to disk.
 */
export async function saveSession(
  sessionId: string,
  messages: NormalizedMessageParam[],
  metadata: Partial<SessionMetadata>,
): Promise<void> {
  const dir = getSessionPath(sessionId)
  await mkdir(dir, { recursive: true })

  const messagesWithIds = ensureMessageIds(messages)

  const data: SessionData = {
    metadata: {
      id: sessionId,
      cwd: metadata.cwd || process.cwd(),
      model: metadata.model || 'claude-sonnet-4-6',
      provider: metadata.provider,
      createdAt: metadata.createdAt || new Date().toISOString(),
      updatedAt: new Date().toISOString(),
      messageCount: messagesWithIds.length,
      summary: metadata.summary,
      lastInputTokens: metadata.lastInputTokens,
      lastOutputTokens: metadata.lastOutputTokens,
    },
    messages: messagesWithIds,
  }

  // Atomic replacement (review #47 P1): write to a temporary sibling file,
  // then rename over transcript.json. A crash mid-write can never leave the
  // existing transcript truncated or partially replaced — readers see either
  // the old file or the complete new one. Same directory guarantees the same
  // filesystem, so rename is atomic (POSIX) / REPLACE_EXISTING (Windows).
  const finalPath = join(dir, 'transcript.json')
  const tmpPath = join(dir, `transcript.json.tmp-${crypto.randomUUID()}`)
  try {
    await writeFile(tmpPath, JSON.stringify(data, null, 2), 'utf-8')
    await rename(tmpPath, finalPath)
  } catch (err) {
    await unlink(tmpPath).catch(() => {}) // best-effort tmp cleanup
    throw err
  }
}

/**
 * Load session from disk.
 */
export async function loadSession(sessionId: string): Promise<SessionData | null> {
  try {
    const filePath = join(getSessionPath(sessionId), 'transcript.json')
    const content = await readFile(filePath, 'utf-8')
    const data = JSON.parse(content) as SessionData
    data.messages = ensureMessageIds(data.messages)
    return data
  } catch {
    return null
  }
}

/**
 * List all sessions.
 */
export async function listSessions(): Promise<SessionMetadata[]> {
  try {
    const dir = getSessionsDir()
    const entries = await readdir(dir)
    const sessions: SessionMetadata[] = []

    for (const entry of entries) {
      try {
        const data = await loadSession(entry)
        if (data?.metadata) {
          sessions.push(data.metadata)
        }
      } catch {
        // Skip invalid sessions
      }
    }

    // Sort by updatedAt descending
    sessions.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))

    return sessions
  } catch {
    return []
  }
}

/**
 * Fork source specification — which session and message to fork from.
 */
export interface ForkSource {
  sessionId: string
  /** Fork point: only messages up to and including this one are copied. */
  messageId?: string
}

/**
 * Fork options.
 */
export interface ForkOptions {
  /**
   * Keep original message IDs instead of regenerating them.
   *
   * Message IDs are only required to be unique within a session, so reusing
   * them across sessions is safe. Useful when the caller stores SDK messages
   * in a database keyed by (sessionId, messageId) and wants the forked
   * transcript to reference the same records.
   *
   * Defaults to `false` (IDs are regenerated).
   */
  preserveIds?: boolean
}

/**
 * Fork a session (create a copy with a new ID).
 *
 * Without messageId: full copy of all messages.
 * With messageId: only messages up to and including that message are copied.
 *
 * Message IDs are regenerated by default; set `preserveIds: true` to keep the
 * original IDs. `_snapshot` metadata is always stripped — fork only supports
 * conversation revert, not file revert (avoids cross-session file conflicts).
 */
export async function forkSession(
  source: ForkSource | string,
  newSessionId?: string,
  options?: ForkOptions,
): Promise<string | null> {
  // Accept both old signature (string) and new ({ sessionId, messageId? })
  const sourceSessionId = typeof source === 'string' ? source : source.sessionId
  const forkMessageId = typeof source === 'string' ? undefined : source.messageId

  const data = await loadSession(sourceSessionId)
  if (!data) return null

  let messages = data.messages

  if (forkMessageId) {
    const idx = messages.findIndex((m) => m.id === forkMessageId)
    if (idx === -1) {
      throw new Error(`Message not found: ${forkMessageId}`)
    }
    messages = messages.slice(0, idx + 1)
  }

  // Strip _snapshot — fork only supports conversation revert, not file revert.
  messages = messages.map((m) => ({
    ...m,
    id: options?.preserveIds ? m.id : crypto.randomUUID(),
    _snapshot: undefined,
  }))

  const forkId = newSessionId || crypto.randomUUID()

  await saveSession(forkId, messages, {
    ...data.metadata,
    id: forkId,
    createdAt: new Date().toISOString(),
    summary: `Forked from session ${sourceSessionId}`,
  })

  return forkId
}

/**
 * Get session messages.
 */
export async function getSessionMessages(
  sessionId: string,
): Promise<NormalizedMessageParam[]> {
  const data = await loadSession(sessionId)
  return data?.messages || []
}

/**
 * Append a message to a session transcript.
 */
export async function appendToSession(
  sessionId: string,
  message: NormalizedMessageParam,
): Promise<void> {
  const data = await loadSession(sessionId)
  if (!data) return

  data.messages.push(message.id ? message : { ...message, id: crypto.randomUUID() })
  data.metadata.updatedAt = new Date().toISOString()
  data.metadata.messageCount = data.messages.length

  await saveSession(sessionId, data.messages, data.metadata)
}

/**
 * Delete a session.
 */
export async function deleteSession(sessionId: string): Promise<boolean> {
  try {
    const { rm } = await import('fs/promises')
    await rm(getSessionPath(sessionId), { recursive: true, force: true })
    return true
  } catch {
    return false
  }
}

/**
 * Get info about a specific session.
 */
export async function getSessionInfo(
  sessionId: string,
  options?: { dir?: string },
): Promise<SessionMetadata | null> {
  const data = await loadSession(sessionId)
  return data?.metadata || null
}

/**
 * Rename a session.
 */
export async function renameSession(
  sessionId: string,
  title: string,
  options?: { dir?: string },
): Promise<void> {
  const data = await loadSession(sessionId)
  if (!data) return

  data.metadata.summary = title
  data.metadata.updatedAt = new Date().toISOString()

  await saveSession(sessionId, data.messages, data.metadata)
}

/**
 * Tag a session.
 */
export async function tagSession(
  sessionId: string,
  tag: string | null,
  options?: { dir?: string },
): Promise<void> {
  const data = await loadSession(sessionId)
  if (!data) return

  ;(data.metadata as any).tag = tag
  data.metadata.updatedAt = new Date().toISOString()

  await saveSession(sessionId, data.messages, data.metadata)
}
